### ISSUE TITLE
[Meta] collection of log improvements

### ISSUE THREAD

**Issue by kennytm** [pingcap/br#259]
This issue collects some quality issues we've identified when trying to debug a problem using the log files alone. Feel free to edit and add more items.

- [ ] In BR, an error due to `context.Canceled` should not produce any log above DEBUG level. This is just visual clutter and mask the real error.
- [ ] In BR, logs of errors from TiKV should include the IP address of the TiKV, so that we don't need to fetch the log from every node in the cluster.
- [ ] In TiKV, the `download` step should record how long the process has taken (whether success or not).

**Comment by YuJuncen** [comment]
I will try to do (6) after #266 merged. (Since #266 make a grate change, fix this before it merges might do some extra work and make things more complex...)
