### ISSUE TITLE
Tracking issue of BR clustered index compatibility

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#790]
Compatibility of BR and clustered index issues: 

- [x] 1. Restore a clustered index backup to TiDB 4.0.x causes data corruption.

<details> <summary> Steps </summary>

```
# Execute on TiDB 5.0
MySQL [(none)]> SET tidb_enable_clustered_index = 1;
MySQL [(none)]> CREATE TABLE composite_primary_key (
 key_a INT NOT NULL,
 key_b INT NOT NULL,
 b CHAR(100),
 PRIMARY KEY (key_a, key_b)
);
MySQL [(none)]> INSERT INTO composite_primary_key VALUES (1, 1, 'aaa'), (2, 2, 'bbb');

# Make a backup
tiup br:nightly backup full -s "local:///backup/clustered"
# Restore the backup on TiDB 4.0.11
tiup br:v4.0.11 restore full -s "local:///backup/clustered" --check-requirements=false

# Execute on TiDB 4.0.11
MySQL [(none)]> select * from test.composite_primary_key;
ERROR 1105 (HY000): [components/tidb_query/src/batch/executors/table_scan_executor.rs:338]: Data is corrupted, missing data for NOT NULL column (offset = 0)
```

</details>

- [x] 2. Restore a non-clustered index backup to TiDB 5.0 causes data corruption.

<details> <summary> Steps </summary>

```
# Execute on TiDB 4.0.11
MySQL [(none)]> CREATE TABLE composite_primary_key (
 key_a INT NOT NULL,
 key_b INT NOT NULL,
 b CHAR(100),
 PRIMARY KEY (key_a, key_b)
);
MySQL [(none)]> INSERT INTO composite_primary_key VALUES (1, 1, 'aaa'), (2, 2, 'bbb');

# Make a backup

# Execute on TiDB 5.0
MySQL [(none)]> SET tidb_enable_clustered_index = 1;
MySQL [(none)]> CREATE TABLE composite_primary_key (
 key_a INT NOT NULL,
 key_b INT NOT NULL,
 b CHAR(100),
 PRIMARY KEY (key_a, key_b)
);

# Restore the backup on TiDB 5.0
tiup br:v4.0.11 restore full -s "local:///backup/notclustered" --check-requirements=false

MySQL [(none)]> select * from test.composite_primary_key;
ERROR 1105 (HY000): invalid data type: unsupported data type `128`
```

</details>

- [x] 3. Restore a clustered index backup to TiDB 4.0.x creates an empty table.

<details> <summary> Steps </summary>

```
# Execute on TiDB 5.0
MySQL [(none)]> SET tidb_enable_clustered_index = 1;
MySQL [(none)]> CREATE TABLE composite_primary_key (
 key_a INT NOT NULL,
 key_b INT NOT NULL,
 b CHAR(100),
 PRIMARY KEY (key_a, key_b)
);
MySQL [(none)]> INSERT INTO composite_primary_key VALUES (1, 1, 'aaa'), (2, 2, 'bbb');

# Make a backup
tiup br:nightly backup full -s "local:///backup/clustered"
# Restore the backup on TiDB 4.0.11
tiup br:nightly restore full -s "local:///backup/clustered"

# Execute on TiDB 4.0.11
MySQL [test]> use test; show tables;
+-----------------------+
| Tables_in_test        |
+-----------------------+
| composite_primary_key |
+-----------------------+
1 row in set (0.000 sec)```

</details>

**Comment by 3pointer** [comment]
for 1. Restore a clustered index backup to TiDB 4.0.x causes data corruption.
With this PR https://github.com/pingcap/br/pull/685, BR can check whether clustered index enabled on this table and stop restore.

for 2. Restore a non-clustered index backup to TiDB 5.0 causes data corruption.
After discuss with @lichunzhu , we both think it's not easy to support this case. we shouldn't skip check-requirements, and let the check failed to avoid this error.

**Comment by zhangjinpeng1987** [comment]
any update?

**Comment by YuJuncen** [comment]
For (1):
After #685, restore would break if `IsCommonHandle` in created table mismatches of how it backed up.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/36239017/111285288-f259c180-867b-11eb-990c-1f1a301c1f79.png">

For (2):
The newest version of BR can restore non-clustered index, even `tidb_enable_clustered_index` is on and will create table as desired.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/36239017/111287935-aceac380-867e-11eb-9f25-afd62fab1ffa.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/36239017/111287967-b4aa6800-867e-11eb-8418-77136f19cb9d.png">

**Comment by IANTHEREAL** [comment]
Consider the following scenario: the user upgrades from 4.0 to 5.0, most of the tables are non-clustered index tables, only a small part of the newly created tables are clustered index (because the clustered index is enabled by default in 5.0, the user has no perception, he may not Understand what a clustered index is). When users encounter problems, they need to quickly downgrade or build a low-version disaster-tolerant cluster.
In this scenario, can the 5.0 backup data be used to restore in 4.0? @zhangjinpeng1987 @YuJuncen

**Comment by YuJuncen** [comment]
@IANTHEREAL Maybe logic backup works: using dumpling and lightning? (Even not so fast)

**Comment by IANTHEREAL** [comment]
I know. How do we explain to users the problem that non-clustered table cannot be restored? And do we want to give users better choices?

**Comment by YuJuncen** [comment]
@IANTHEREAL Eh, I have checked the [document](https://docs.pingcap.com/zh/tidb/v5.0/system-variables#tidb_enable_clustered_index-从-v500-rc-版本开始引入) yet. Seems 5.0 would not enable clustered index by default, so by the time user made a table using clustered index, they would probably have perception about what they are doing?

**Comment by kennytm** [comment]
i thought you need to explicitly use the `CLUSTERED`/`NONCLUSTERED` syntax in the `CREATE TABLE` nowadays?

**Comment by IANTHEREAL** [comment]
@YuJuncen It is not 5.0 rc, but 5.0 GA is enabled by default, you can confirm it. But it can’t solve the user’s doubts about why the non-clustered table cannot be restored after learning the clustered index. I am mainly concerned about this doubt and the demand behind the doubt.

**Comment by IANTHEREAL** [comment]
@kennytm This issue has been discussed many times in the cluster index spec review, and the final conclusion seems to be that this concept does not require users to understand by default.

**Comment by IANTHEREAL** [comment]
can we close it?
