### ISSUE TITLE
Tracking issue of unifying duplicate packages between BR and Lightning

### ISSUE THREAD

**Issue by overvenus** [pingcap/br#800]
After #665, BR repo contains both BR code and TiDB-Lightning code. 

There are some packages are very similar, they should be unified to reduce duplicate code and improve maintenance efficiency.

- [ ] 1. `pkg/glue` and `pkg/lightning/glue`
- [ ] 2. `pkg/logutil` and `pkg/lightning/log`
- [ ] 3. `pkg/checksum`, `pkg/lightning/restore/checksum.go` and `pkg/lightning/verification`
- [ ] 4. `pkg/kv` and `pkg/lightning/backend`
- [ ] 5. `pkg/httputil` and `pkg/lightning/common/security.go`
- [ ] 6. `pkg/utils/worker.go` and `pkg/lightning/worker`
- [ ] 7. `pkg/manual` and `pkg/lightning/manual`
