### ISSUE TITLE
RawKV Backup & Restore Project

### ISSUE THREAD

**Issue by 3pointer** [pingcap/br#86]
# RawKV Backup & Restore Project

# Abstract

In this project we needs focus on [TiKV](https://github.com/tikv/tikv) and [BR](https://github.com/pingcap/br) project. and we need to
- Implement Raw KV backup and restore based on current [BR](https://github.com/pingcap/br) project.

### Problem Statement

For now TiKV is an independent CNCF project, the ability of backup and restore data is become more important, so we need to implement backup and restore data in TiKV with BR.
Raw KV is a concept of TiKV and irrelevant with tidb, current BR already support backup Txn KV from TiDB TiKV cluster and restore Txn KV data to new cluster.
we can reuse above process to implement Raw KV backup and restore, so the main process can be divided into two section.
Backup:
- Use BR Backup Command to send backup request to TiKV cluster.
- TiKV receive backup request then start to backup Raw KV, then put data into specify storage(local storage for now).

Restore:
- Use BR Restore Command to send restore request to TiKV cluster.
- TiKV restore data from specify storage.

# Success Criteria

- With [BR](https://github.com/pingcap/br) program, one can backup Raw KV from exist TiKV cluster, and restore to new TiKV cluster successfully.

# TODO list

- [x] TiKV use RegionIterator to scan Raw KV by given key range. *(500 points / medium)* [detail](https://github.com/tikv/tikv/issues/6213)
- [x] TiKV restore raw kv depends on current TiKV restore logic. *(500 points / medium)* [detail](https://github.com/tikv/tikv/issues/6220)
- [ ] BR support communicate with only TiKV cluster. *(300 points / medium)*
- [ ] BR support restore Raw KV command. *(500 points / medium)*
- [ ] BR support backup Raw KV command. *(500 points / medium)*

## Difficulty

* Easy

## Score

* 2300

## Mentor(s)

* @3pointer  

## Recommended skills

* Go language
* Basic understanding of TiKV

# References

- [BR introduction](https://pingcap.com/docs-cn/dev/how-to/maintain/backup-and-restore/br/#%E5%A4%87%E4%BB%BD%E5%8E%9F%E7%90%86)
- [TiKV Storage Source Code Reading](https://pingcap.com/blog-cn/tikv-source-code-reading-11/)

**Comment by youjiali1995** [comment]
I want to join in this task~

**Comment by breeswish** [comment]
I want to join in this task~

**Comment by GregoryIan** [comment]
@3pointer any documents about it?
